### ISSUE TITLE
text looks bad

### ISSUE THREAD

**Issue by redreceipt** [ApollosProject/apollos-embeds#225]
## Problem Statement

[Linear issue](https://linear.app/differential/issue/APO-206/battlecreek-web-embed-displaying-broken-text)
PR Branch Name: `apo-206-battlecreek-web-embed-displaying-broken-text`

Sometimes text looks really bad

## Resolution Criteria

- [ ] Text looks good

## How to reproduce

- Go here: https://battlecreekchurch.webflow.io/
- Click "Family Reunion Part 2"

## Screenshots/Recordings

https://github.com/ApollosProject/apollos-embeds/assets/2659478/255522f5-aa9d-476e-9370-8c2fa36f7f83

**Comment by rajitharussel** [comment]
@redreceipt I was trying to recreate this issue but looks like this is not originally from this repo. here are the observations


these are the styles that caused to issue. the first one is from our side added here > 

https://github.com/ApollosProject/apollos-embeds/blob/f6249035149c7ddc41b24291cf00e0fc5986705e/packages/web-shared/ui-kit/Longform/Longform.styles.js#L21

![Screenshot 2024-07-03 at 16 59 49](https://github.com/ApollosProject/apollos-embeds/assets/138706838/9cd26f1c-2710-4ddd-9108-dcdb0376a90c)

as you can see they have overridden the font size but the new `line-height` won't apply because they haven't used the `!important` key. so I applied it from the browser and now it works.


<img width="1420" alt="Screenshot 2024-07-03 at 17 06 39" src="https://github.com/ApollosProject/apollos-embeds/assets/138706838/1ffa8c6a-048a-4437-bcaf-69cf125045d3">

so this can be fixed from the CSS file coming from here.

https://cdn.prod.website-files.com/66350c65ca55dcf714ea2d03/css/battlecreekchurch.webflow.bce7e345f.css

**Comment by rajitharussel** [comment]
@redreceipt we can close this right?
